### PR TITLE
Added a calculator pugin

### PR DESCRIPTION
**Pull request by JuanPotato**
:\ I messed up a bit while editing readme but its good now :)

### CODE REVIEW

**Comment by rockneurotiko** [comment]
Can you squash the commits into one or two? :)
(also there are a merge pull request commit XD)

And in the code, `import requests` at top ;-)

To re-generate the plugins table, I created a script, just run:

```
source env/bin/activate
./scripts/generate-plugins-table.py
```

And answer Y if you want the changes :)

**Comment by JuanPotato** [comment]
yeah I accidently put re instead of requests. About the commits, I don't know what happened XD, and I'm not sure how to make them into one or two commits. Should I just make a new merge request with just the two commits?

**Comment by rockneurotiko** [comment]
No problem, I'll squash them manually, next time, before push to your repository, use interactive rebase to squash, it's a powerful tool! (git rebase)

**Comment by JuanPotato** [comment]
Alright, thanks for the tip :)

**Comment by rockneurotiko** [comment]
Merged here 4c02bcc6995baa
Thanks a lot for the plugins! ^^

**Pull request closed without merging**
