### PR TITLE
New money plugin

### PR DESCRIPTION
**Pull request by JuanPotato**
I was not able to test this plugin as an actual plugin but I tested the function and it worked.

### CODE REVIEW

**Comment by rockneurotiko** [comment]
Thanks for the awesome work!!

Some comments :)

The imports, do it in the top of the file.
The matches index, according to you reg expression, would be 1, 2 and 3, and not 0, 1 and 2. See:

```
In [11]: a = "^!m(oney)? (\w+) ([\d\.]+) (\w+)$"

In [12]: b = "!money eur 1 usd"

In [13]: re.search(a,b).groups()
Out[13]: ('oney', 'eur', '1', 'usd')
```

You can see that index 0 is the optional "oney" :) Also, if it's not present that group it will be None:

```
In [15]: re.search(a,"!m eur 1 usd").groups()
Out[15]: (None, 'eur', '1', 'usd')
```

The bot is in python3, so urllib2 (if you would put the import on top, travis would tell you this) is not present, you can use requests instead, or urllib.

And at least, try to use the format string, instead of concatenade, for example:
`returnText = amount + " " + fromCur + " is " + moneyMatches.group(1) + " " + toCur`
becomes:
`returnText = "{} {} is {} {}".format(amount, fromCur, moneyMatches.group(1), toCur)`
I think that is more readable =D (and avoid some runtime errors)

You can change yourself, or if you don't want, I'll do it myself.

Once again, thanks for this! :)

**Comment by rockneurotiko** [comment]
Ou, almost forgot, and add to README.md the plugin ^^

**Comment by rockneurotiko** [comment]
Are you going to finish fixing this or I do it?

**Comment by JuanPotato** [comment]
You can do it, sorry, I messed up a bit somewhere and never came back to this ._.

**Comment by rockneurotiko** [comment]
Manually merged here 85b6725d and corrected (if you want to see the changes) in 968f6935

**Pull request closed without merging**
